version: '3.8'
services:
  dashboard:
    build: .
    image: wmsolar/dashboard:latest
    container_name: dashboard
    networks:
      - overlay
    privileged: true
    ports:
      - "8000:8000"
    working_dir: /usr/src/dashbd
    volumes:
      - .:/usr/scr/dashbd

networks:
   overlay:
